env:
  browser: true
  node: true
  es6: true
plugins:
  - react
  - prettier
parser: babel-eslint
extends:
  - airbnb
  - prettier
  - prettier/react
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  jsx-a11y/anchor-is-valid:
    - 1
  prettier/prettier: error
settings:
  import/resolver:
    webpack:
      config: ./webpack.config.js
